image: node:12

definitions:
  steps:
    - step: &lint
        name: lint
        caches:
          - node
        script:
          - npm install
          - npm run lint

pipelines:
  default:
    - step: *lint
