image: node:12

definitions:
  steps:
    - step: &test
        name: test
        caches:
          - node
        script:
          - npm install
          - npm run test
    - step: &lint
        name: lint
        caches:
          - node
        script:
          - npm install
          - npm run lint

pipelines:
  default:
    - parallel:
        - step: *test
        - step: *lint
